version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - aws cloudformation package --template-file sam.yaml --output-template-file output-sam.yaml --s3-bucket qbd-api-deployment-artifacts
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/qbd-api-1.0.0-SNAPSHOT-all.jar
    - output-sam.yaml
