version: '3.3'

services:
   db:
     platform: linux/amd64
     image: mysql:5.7
     container_name: db
     ports:
       - 3306:3306
     restart: always
     volumes:
       - .:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: adminpass
       MYSQL_DATABASE: qbd
       MYSQL_USER: user
       MYSQL_PASSWORD: secret

