AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS QBD API - example::example
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'ExampleFunction'
      Handler: ca.airspeed.qbdapi.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/exploded
      MemorySize: 768
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 25
      Environment:
        Variables:
          MICRONAUT_ENVIRONMENTS: prod
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  QbdApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: QbdApi