AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS QBD API - example::example
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Parameters:
  NetworkStack:
    Type: String
    Description: The name of your stack that has the Subnet and Security Group you want to use for this stack.
    MaxLength: 128
    AllowedPattern: ^[A-Za-z0-9\-]+$
    ConstraintDescription: must only contain letters (uppercase and lowercase), numbers and hyphens
  DbUsername:
    Type: String
    Default: 'qbairspeed'
  DbPassword:
    Type: String
    Default: 'H46Sa4X'
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ca.airspeed.qbdapi.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/libs/qbd-api-1.0.0-SNAPSHOT-all.jar
      MemorySize: 768
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AmazonSSMReadOnlyAccess
      Timeout: 60
      Environment:
        Variables:
          MICRONAUT_ENVIRONMENTS: prod
          DB_USERNAME: !Ref DbUsername
          DB_PASSWORD: !Ref DbPassword
      Events:
        GetResource:
          Type: Api
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /{proxy+}
            Method: any
      VpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStack}-SecurityGroupID
        SubnetIds:
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStack}-Lambda1SubnetID

Outputs:
  QbdApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: QbdApi