micronaut:
  application:
    name: qbd-api
  data:
    pageable:
      max-page-size: 10
  server:
    contextPath: "/qbd-api"
  security:
    token:
      jwt:
        signatures:
          jwks:
            awscognito:
              url: 'https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json'

jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: 'ca.airspeed.qbdapi.adapter.out.persistence'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update

endpoints:
  all:
    path: /manage
    sensitive: false
