micronaut:
  application:
    name: qbd-api
  data:
    pageable:
      max-page-size: 10
  router:
    static-resources:
      swagger:
        paths:
          - classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths:
          - classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths:
          - classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths:
          - classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    context-path: /qbd-api
  security:
    intercept-url-map:
      -
        pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
    reject-not-found: false
    token:
      jwt:
        signatures:
          jwks:
            awscognito:
              url: 'https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json'

jackson:
  bean-introspection-module: true
  dateFormat: "yyyy-MM-dd'T'HH:mm:ssXXX"
  timeZone: 'America/Winnipeg'
---
datasources:
  default:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: VALIDATE
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
jpa:
  default:
    entity-scan:
      packages: 'ca.airspeed.qbdapi.adapter.out.persistence'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        naming:
          physical-strategy: 'ca.airspeed.qbdapi.adapter.out.persistence.RawPhysicalNamingStrategy'

endpoints:
  all:
    path: /manage
    sensitive: false
